version: "3.9"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    container_name: keycloak
    command: start-dev --import-realm --hostname=http://keycloak:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8080:8080"
    networks:
      - poc-net
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /realms/poc-realm HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q 'poc-realm'"]
      interval: 5s
      timeout: 5s
      retries: 30

  crud-service:
    build: ./crud-service
    container_name: crud-service
    # Não publicamos porta no host de propósito: só o sidecar deve falar com esse serviço.
    #ports:
    #- "8081:8081"
    networks:
      - poc-net


  oauth-sidecar:
    build: ./oauth-sidecar
    container_name: oauth-sidecar
    depends_on:
      keycloak:
        condition: service_healthy
      crud-service:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - poc-net

networks:
  poc-net:
    driver: bridge
