server:
  port: 8083

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:h2:mem:billingdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.poc.billing: INFO
